name: demo-influencer-data-management
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40000:40000"
    environment:
      # Spring Boot 环境变量
      - INFLUENCER_DB_URL=jdbc:postgresql://123.60.84.219:5432/influencer-data-management
      - INFLUENCER_DB_USERNAME=postgres
      - INFLUENCER_DB_PASSWORD=TangentAI666
      - DASH_SCOPE_API_KEY=sk-a8358f9902d64f29a6890fb0bb29c6e9
      - DASH_SCOPE_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode
      - DASH_SCOPE_CHAT_MODEL=qwen-max
      - DASH_SCOPE_EMBEDDING_MODEL=text-embedding-v4
      # Node.js 环境变量
      - NODE_ENV=production
      - PORT=3000