spring.application.name=creator-data-management

spring.datasource.url=${INFLUENCER_DB_URL}
spring.datasource.username=${INFLUENCER_DB_USERNAME}
spring.datasource.password=${INFLUENCER_DB_PASSWORD}

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=${DASH_SCOPE_API_KEY}
spring.ai.openai.base-url=${DASH_SCOPE_BASE_URL}
spring.ai.openai.chat.options.model=${DASH_SCOPE_CHAT_MODEL}
spring.ai.openai.embedding.base-url=${DASH_SCOPE_BASE_URL}
spring.ai.openai.embedding.options.model=${DASH_SCOPE_EMBEDDING_MODEL}
spring.ai.openai.embedding.options.dimensions=2048