spring.application.name=creator-data-management

spring.datasource.url=${INFLUENCER_DB_URL}
spring.datasource.username=${INFLUENCER_DB_USERNAME}
spring.datasource.password=${INFLUENCER_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=${DASH_SCOPE_API_KEY}
spring.ai.openai.base-url=${DASH_SCOPE_BASE_URL}
spring.ai.openai.chat.options.model=${DASH_SCOPE_CHAT_MODEL}

spring.jackson.property-naming-strategy=SNAKE_CASE

huawei.obs.endpoint=https://obs.cn-east-3.myhuaweicloud.com
huawei.obs.accessKey=HPUAWFBUMXNUTDRIRPIW
huawei.obs.secretKey=EZpI8cbCsLZtwfnTJl4V5O9vVv18gWTSmiWIXFMY
huawei.obs.bucketName=influencer-data-management-dev
huawei.obs.bucketPrefix=
huawei.obs.bucketPath=https://influencer-data-management-dev.obs.cn-east-3.myhuaweicloud.com